# Generated by Django 5.2.4 on 2025-07-10 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid Egyptian phone number (10 digits starting with 01)', regex='^01[0-9]{9}$')], verbose_name='Phone Number'),
        ),
    ]
